title: "The Notorious RBF Blog"
author: "NotoriousRBF"
description: "Kernel tricks, oncology, and biostatistics"
theme: minimal
plugins:
  - jekyll-feed

permalink: /:year/:month/:day/:title/


future: true

baseurl: "/blog" 
